<a href="https://colab.research.google.com/github/Anas1657/MACHINE-LEARNING-2/blob/main/numpy_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
np.arange(.4,10.4) #take decimal value in arange function
#arange function alternative of range fucntion that take float values

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

linspace used to generate dataset in number between particualr range

In [ ]:
np.linspace(1,5 , 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,20)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [ ]:
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4)) #3 row and 4 column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr=np.ones((3,4))

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr1=np.eye(5)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [ ]:
np.random.rand(2,3) #generate random data
#average or mean can be any thing

array([[0.63752358, 0.44984532, 0.94624975],
       [0.22450541, 0.8216874 , 0.58692478]])

In [ ]:
np.random.randn(2,3)

array([[-1.73508032, -0.39097592,  0.65333509],
       [ 1.58933622, -1.54456574,  0.25070979]])

**rand:** Generates random numbers uniformly distributed over the range [0, 1), meaning each number within this range is equally likely to be generated. The numbers are drawn from a uniform distribution, and you can specify the shape of the output array. For example, numpy.random.rand(3,2) would generate an array of shape (3,2) with random numbers uniformly distributed between 0 and 1.

**randn:** Generates random numbers from the standard normal distribution, which is a Gaussian distribution with a mean of 0 and a variance of 1. The numbers are thus distributed according to the bell curve, centered around 0, and with a standard deviation of 1. The function can also generate arrays of random numbers with specified dimensions. For instance, numpy.random.randn(3,2) would produce an array of shape (3,2) with random numbers drawn from the standard normal distributio

In [ ]:
arr2=np.random.randint(1,5,(3,4))

In [ ]:
arr2.size

12

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.reshape(6,2)

array([[3, 1],
       [2, 4],
       [2, 3],
       [2, 4],
       [1, 3],
       [1, 4]])

In [ ]:
arr2.reshape(3,4)

array([[3, 1, 2, 4],
       [2, 3, 2, 4],
       [1, 3, 1, 4]])

In [ ]:
arr2.reshape(2,3,2)

array([[[3, 1],
        [2, 4],
        [2, 3]],

       [[2, 4],
        [1, 3],
        [1, 4]]])

In [ ]:
arr4=np.random.randint(1,10,(5,6))

In [ ]:
arr4

array([[9, 9, 9, 5, 9, 3],
       [4, 8, 1, 7, 5, 1],
       [4, 7, 7, 2, 4, 1],
       [8, 8, 8, 8, 3, 1],
       [7, 7, 6, 5, 7, 9]])

In [ ]:
arr4>5

array([[ True,  True,  True, False,  True, False],
       [False,  True, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [ True,  True,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True]])

In [ ]:
arr4[arr4>5]

array([9, 9, 9, 9, 8, 7, 7, 7, 8, 8, 8, 8, 7, 7, 6, 7, 9])

In [ ]:
arr4[0][0]

9

In [ ]:
arr4

array([[9, 9, 9, 5, 9, 3],
       [4, 8, 1, 7, 5, 1],
       [4, 7, 7, 2, 4, 1],
       [8, 8, 8, 8, 3, 1],
       [7, 7, 6, 5, 7, 9]])

In [ ]:
arr4[0,[0,1]]

array([9, 9])

In [ ]:
arr4[2:4,[2,3]]

array([[7, 2],
       [8, 8]])

In [ ]:
arr5=np.random.randint(1,3,(3,3))
arr6=np.random.randint(1,3,(3,3))


In [ ]:
arr5


array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [ ]:
arr6

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [ ]:
arr5+arr6

array([[3, 3, 3],
       [2, 4, 3],
       [3, 3, 4]])

In [ ]:
arr5@arr6 #used for matrix multiplication

array([[ 8, 10,  8],
       [ 7,  9,  7],
       [ 6,  7,  6]])

In [ ]:
arr5*arr6 #give indexwise multiplication

array([[2, 2, 2],
       [1, 4, 2],
       [2, 2, 4]])

In [ ]:
arr5/0

<ipython-input-64-0b5f13e22baf>:1: RuntimeWarning: divide by zero encountered in divide
  arr5/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

**Broadcasting**

In [ ]:
arr=np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
b=np.array([[3,4,5]])

In [ ]:
arr+b.T

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [ ]:
b.T

array([[3],
       [4],
       [5]])

In [ ]:
arr1

array([[2, 7, 9, 3, 5, 3],
       [8, 3, 6, 4, 6, 9],
       [6, 3, 4, 4, 1, 5],
       [4, 8, 8, 6, 1, 3],
       [1, 6, 4, 5, 9, 8]])

In [ ]:
np.log10(arr1)

array([[0.30103   , 0.84509804, 0.95424251, 0.47712125, 0.69897   ,
        0.47712125],
       [0.90308999, 0.47712125, 0.77815125, 0.60205999, 0.77815125,
        0.95424251],
       [0.77815125, 0.47712125, 0.60205999, 0.60205999, 0.        ,
        0.69897   ],
       [0.60205999, 0.90308999, 0.90308999, 0.77815125, 0.        ,
        0.47712125],
       [0.        , 0.77815125, 0.60205999, 0.69897   , 0.95424251,
        0.90308999]])

In [ ]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 8.10308393e+03, 2.00855369e+01,
        1.48413159e+02, 2.00855369e+01],
       [2.98095799e+03, 2.00855369e+01, 4.03428793e+02, 5.45981500e+01,
        4.03428793e+02, 8.10308393e+03],
       [4.03428793e+02, 2.00855369e+01, 5.45981500e+01, 5.45981500e+01,
        2.71828183e+00, 1.48413159e+02],
       [5.45981500e+01, 2.98095799e+03, 2.98095799e+03, 4.03428793e+02,
        2.71828183e+00, 2.00855369e+01],
       [2.71828183e+00, 4.03428793e+02, 5.45981500e+01, 1.48413159e+02,
        8.10308393e+03, 2.98095799e+03]])

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

9