<a href="https://colab.research.google.com/github/Anas1657/MACHINE-LEARNING-2/blob/main/Numpy_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]

In [ ]:
arr=np.array(l)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
arr1=np.array([[1,2,3],[2,3,4]])

In [ ]:
arr.ndim #tells the dimension

1

In [ ]:
arr1.ndim

2

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
mat=np.matrix(l)

In [ ]:
np.asanyarray(l) #convert any form of data into arary

array([1, 2, 3, 4])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
a=arr

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr[0]=100

In [ ]:
arr

array([100,   2,   3,   4])

In [ ]:
a #process is called solocopy

array([100,   2,   3,   4])

In [ ]:
b=np.copy(arr) #deep copy concept

In [ ]:
b[0]=200

In [ ]:
arr

array([100,   2,   3,   4])

In [ ]:
b

array([200,   2,   3,   4])

***fromfunction*** take function as an arguement bases on taht function it take action

In [ ]:
np.fromfunction(lambda i,j : i==j , (3,3)) #3,3 shape

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [ ]:
iterable=(i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('23 45 67',sep= ' ')

array([23., 45., 67.])

In [ ]:
np.fromstring('23,45,67',sep= ',')

array([23., 45., 67.])

In [ ]:
arr

array([100,   2,   3,   4])

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.ndim

1

In [ ]:
arr1.ndim

2

In [ ]:
arr.size #telll size of araray

4

In [ ]:
arr1.size

6

In [ ]:
arr.shape

(4,)

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('int64')