<a href="https://colab.research.google.com/github/Anas1657/MACHINE-LEARNING-2/blob/main/numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#ARRAY manipulation

In [ ]:
arr=np.random.randint(1,10,(4,4,))

In [ ]:
arr

array([[2, 1, 2, 4],
       [3, 4, 7, 9],
       [7, 7, 6, 2],
       [9, 8, 9, 4]])

In [ ]:
arr.reshape(8,2)

array([[2, 1],
       [2, 4],
       [3, 4],
       [7, 9],
       [7, 7],
       [6, 2],
       [9, 8],
       [9, 4]])

In [ ]:
arr.T

array([[2, 3, 7, 9],
       [1, 4, 7, 8],
       [2, 7, 6, 9],
       [4, 9, 2, 4]])

In [ ]:
arr.flatten() #2d to 1D

array([2, 1, 2, 4, 3, 4, 7, 9, 7, 7, 6, 2, 9, 8, 9, 4])

In [ ]:
np.expand_dims(arr,axis=1) #ek dimension prev wale array se bda hojyga

array([[[2, 1, 2, 4]],

       [[3, 4, 7, 9]],

       [[7, 7, 6, 2]],

       [[9, 8, 9, 4]]])

In [ ]:
data=np.array([[1],[2],[3]])

In [ ]:
np.squeeze(data) #2d to 1d

array([1, 2, 3])

In [ ]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
np.roll(data,2) #data ko rotate kr dega purani position se

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Binary operation

In [ ]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [ ]:
arr1

array([[8, 9, 9, 9],
       [9, 1, 5, 9],
       [3, 1, 5, 9]])

In [ ]:
arr2

array([[9, 7, 6, 4],
       [6, 5, 5, 7],
       [5, 2, 4, 7]])

In [ ]:
#string operation

In [ ]:
arr4=np.array(["emash","anas"])

In [ ]:
arr4

array(['emash', 'anas'], dtype='<U5')

In [ ]:
np.char.upper(arr4)

array(['EMASH', 'ANAS'], dtype='<U5')

In [ ]:
np.char.capitalize(arr4)

array(['Emash', 'Anas'], dtype='<U5')

In [ ]:
#mathematicla fucnc

In [ ]:
arr1

array([[8, 9, 9, 9],
       [9, 1, 5, 9],
       [3, 1, 5, 9]])

In [ ]:
np.sin(arr1)

array([[ 0.98935825,  0.41211849,  0.41211849,  0.41211849],
       [ 0.41211849,  0.84147098, -0.95892427,  0.41211849],
       [ 0.14112001,  0.84147098, -0.95892427,  0.41211849]])

In [ ]:
#cos tan ,log10,power(arr1,2),exp,mean,median,no mode operation

In [ ]:
#arithmetic operation

In [ ]:
arr1

array([[8, 9, 9, 9],
       [9, 1, 5, 9],
       [3, 1, 5, 9]])

In [ ]:
arr2

array([[9, 7, 6, 4],
       [6, 5, 5, 7],
       [5, 2, 4, 7]])

In [ ]:
np.subtract(arr1,arr2)

array([[-1,  2,  3,  5],
       [ 3, -4,  0,  2],
       [-2, -1,  1,  2]])

In [ ]:
arr1,arr2

(array([[8, 9, 9, 9],
        [9, 1, 5, 9],
        [3, 1, 5, 9]]),
 array([[9, 7, 6, 4],
        [6, 5, 5, 7],
        [5, 2, 4, 7]]))

In [ ]:
np.power(arr2,arr1)

array([[43046721, 40353607, 10077696,   262144],
       [10077696,        5,     3125, 40353607],
       [     125,        2,     1024, 40353607]])

In [ ]:
#statistical operation

In [ ]:
np.mean(arr1)

6.416666666666667

In [ ]:
#mean ,median,std

In [ ]:
#sort,search & counting func.

In [ ]:
arr6=np.array([2,3,4,5,7,1])

In [ ]:
np.sort(arr6)

array([1, 2, 3, 4, 5, 7])

In [ ]:
np.searchsorted(arr6,6)

6

In [ ]:
arr7=np.array([0,23,4,34,5545,2432424,3424,54,34])

In [ ]:
np.count_nonzero(arr7)

8

In [ ]:
np.where(arr7>56)

(array([4, 5, 6]),)

In [ ]:
np.extract(arr7>34,arr7)

array([   5545, 2432424,    3424,      54])

In [ ]:
#byte swapping

In [ ]:
arr1

array([[8, 9, 9, 9],
       [9, 1, 5, 9],
       [3, 1, 5, 9]])

In [ ]:
arr1.byteswap()

array([[576460752303423488, 648518346341351424, 648518346341351424,
        648518346341351424],
       [648518346341351424,  72057594037927936, 360287970189639680,
        648518346341351424],
       [216172782113783808,  72057594037927936, 360287970189639680,
        648518346341351424]])

In [ ]:
#copies & views

In [ ]:
arr1

array([[8, 9, 9, 9],
       [9, 1, 5, 9],
       [3, 1, 5, 9]])

In [ ]:
a=np.copy(arr1)

In [ ]:
b=arr1.view()

In [ ]:
b

array([[8, 9, 9, 9],
       [9, 1, 5, 9],
       [3, 1, 5, 9]])

In [ ]:
b[0]=234

In [ ]:
b

array([[234, 234, 234, 234],
       [  9,   1,   5,   9],
       [  3,   1,   5,   9]])

In [ ]:
#matrix libraray

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#linear algebra

In [ ]:
arr1

AttributeError: 'numpy.ndarray' object has no attribute 'update'

In [ ]:
arr2

array([[9, 7, 6, 4],
       [6, 5, 5, 7],
       [5, 2, 4, 7]])

In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8,],[9,8,7,6]])

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [ ]:
arr1.shape

(3, 4)

In [ ]:
arr2.shape

(3, 4)

In [ ]:
np.dot(arr1,arr2)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
arr1=arr1.reshape(4,3)

In [ ]:
arr2=arr2.reshape(3,4)

In [ ]:
np.dot(arr1,arr2)

array([[ 36,  23,  28,  39],
       [ 96,  65,  73,  93],
       [156, 107, 118, 147],
       [144, 103, 107, 123]])